import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
import {readFileSync,existsSync,mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import {enterMenu} from './enter-game.mjs';
const html=readFileSync('offline/Special-Chess-Offline.html','utf8');let endpoint,browser,child;
const front=createServer((req,res)=>{res.writeHead(200,{'Content-Type':req.url.endsWith('online-config.json')?'application/json':'text/html'});res.end(req.url.endsWith('online-config.json')?JSON.stringify({server:endpoint}):html);});
try{
 await new Promise(r=>front.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${front.address().port}`,url=origin+'/IAHCARUS-Idle/';child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'0',GUEST_DUEL_ONLY:'true',DUEL_ALLOWED_ORIGINS:origin},stdio:['ignore','pipe','pipe']});endpoint=`http://127.0.0.1:${await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server timeout')),5000);child.stdout.on('data',d=>{const m=String(d).match(/port (\d+)/);if(m){clearTimeout(timer);resolve(Number(m[1]));}});})}`;
 browser=await chromium.launch({executablePath:existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined,args:['--no-sandbox','--enable-unsafe-swiftshader']});const errors=[],shaderErrors=[];
 async function player(){const context=await browser.newContext({viewport:{width:1000,height:850}});await context.addInitScript(()=>{localStorage.setItem('special-chess-graphics-quality','low');localStorage.setItem('special-chess-reduced','true');localStorage.setItem('special-chess-profile',JSON.stringify({xp:0,economy:{credits:2000,premium:300,owned:['nova','phantom','dragon']}}));});const p=await context.newPage();p.setDefaultTimeout(45000);p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/shader|VALIDATE_STATUS|THREE.WebGLProgram/i.test(m.text()))shaderErrors.push(m.text());});return p;}
 const a=await player();let sockets=0;a.on('websocket',()=>sockets++);await a.goto(url);await enterMenu(a);await a.locator('[data-menu-bg]').click();await a.locator('#bg-time').selectOption('10');await a.locator('#bg-skin').selectOption('nova');await a.locator('#bg-bots').click();await a.waitForSelector('#bg-stage canvas');await a.locator('#bg-map-toggle').click();await a.locator('[data-bg-piece="n"]').click();await a.locator('[data-bg-cell="44"]').click();await a.locator('#bg-lock').click();assert.match(await a.locator('#bg-order-status').innerText(),/ล็อก ม้า E6/);await a.waitForFunction(()=>document.querySelector('#bg-round').textContent.startsWith('รอบ 2'));assert.equal(sockets,0,'offline BG must never open a socket');assert.match(await a.locator('#bg-hand-count').innerText(),/หมาก/);await a.locator('#bg-close').click();assert.equal(await a.locator('#battleground').isVisible(),false);
 await a.locator('[data-menu-bg]').click();await a.locator('#bg-connect').click();await a.waitForFunction(()=>document.querySelector('#bg-connection').textContent==='เชื่อมต่อแล้ว');await a.locator('#bg-time').selectOption('30');await a.locator('#bg-create').click();await a.waitForFunction(()=>document.querySelector('#bg-code').textContent.includes('ห้อง'));const code=(await a.locator('#bg-code').innerText()).match(/[A-F0-9]{6}/)[0];
 const others=[];for(const skin of ['phantom','dragon','nova']){const p=await player();await p.goto(url);await enterMenu(p);await p.locator('[data-menu-bg]').click();await p.locator('#bg-skin').selectOption(skin);await p.locator('#bg-connect').click();await p.waitForFunction(()=>document.querySelector('#bg-connection').textContent==='เชื่อมต่อแล้ว');await p.locator('#bg-room-input').fill(code.toLowerCase());await p.locator('#bg-join').click();await p.locator('#bg-ready').waitFor({state:'visible'});others.push(p);}
 await a.evaluate(()=>navigator.clipboard.writeText=async text=>window.bgInvite=text);await a.locator('#bg-copy').click();const link=await a.evaluate(()=>window.bgInvite);assert.equal(new URL(link).searchParams.get('bg'),code);assert.equal(new URL(link).searchParams.has('token'),false);
 const players=[a,...others];for(const p of players)await p.locator('#bg-ready').click();for(const p of players)await p.locator('#bg-stage canvas').waitFor({state:'visible'});await a.locator('#bg-map-toggle').click(); // retained tactical map from the bot game is still visible, toggle closed if needed
 if(!await a.locator('#bg-map').isVisible())await a.locator('#bg-map-toggle').click();for(const p of others)await p.locator('#bg-map-toggle').click();
 for(const p of players){await p.locator('[data-bg-piece="p"]').click();await p.locator('[data-bg-cell="44"]').click();await p.locator('#bg-lock').click();if(p===a)await others[0].waitForFunction(()=>document.querySelector('#bg-order-status').textContent.includes('ส่งคำสั่ง 1/4'));}
 await a.waitForFunction(()=>document.querySelector('#bg-round').textContent.startsWith('รอบ 2'));assert.match(await a.locator('#bg-hand-count').innerText(),/14 หมาก/);for(const p of others)await p.waitForFunction(()=>document.querySelector('#bg-round').textContent.startsWith('รอบ 2'));
 await a.waitForTimeout(1300);assert.match(await a.locator('#bg-feed').innerText(),/ยึดเบี้ย/);assert.equal(await a.locator('#bg-stage canvas').count(),1);
 mkdirSync('test-results',{recursive:true});await a.locator('#bg-map-toggle').click();await a.screenshot({path:'test-results/battleground-desktop.png'});for(const viewport of [{width:390,height:844},{width:320,height:568}]){await a.setViewportSize(viewport);assert.equal(await a.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await a.evaluate(()=>{const root=document.querySelector('#battleground');return root.scrollHeight>root.clientHeight+1;}),false);await a.screenshot({path:`test-results/battleground-${viewport.width}.png`});}
 // Explicitly leave three seats: last survivor result and credit payout must be visible.
 for(const p of others)await p.locator('#bg-close').click();await a.locator('#bg-outcome').waitFor({state:'visible'});assert.match(await a.locator('#bg-outcome').innerText(),/VICTORY/);assert.equal(await a.evaluate(()=>JSON.parse(localStorage.getItem('special-chess-profile')).economy.credits),2650);await a.locator('#bg-again').click();await a.locator('#bg-ready').waitFor({state:'visible'});assert.match(await a.locator('#bg-players').innerText(),/รอเพื่อน/);assert.deepEqual(errors,[]);assert.deepEqual(shaderErrors,[]);console.log('PASS: offline 3-bot round with no socket, real 4-device room, skins/readiness, private invite, simultaneous capture into hand, skin execution shader, 320/390px layout, last-survivor payout and rematch.');
}finally{await browser?.close();child?.kill();await new Promise(r=>front.close(r));}
