import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {WebSocket} from 'ws';
import {newBattleground,submitDeployment,resolveDeployments,deploymentTargets,botDeployment} from '../shared/battleground.js';
import {readProfile,isSkinUnlocked,equipPiece} from '../src/profile.ts';
import {buyShopItem,trialPremium,readEconomy,shopCatalog} from '../shared/economy.js';
import {normalizeCosmetics} from '../shared/cosmetics.js';
import {executionFrame} from '../src/skin-execution.ts';
test('deployment validates a real hand, bounds and occupied friendly cells',()=>{const g=newBattleground();for(const order of [{type:'x',cell:0},{type:'p',cell:100},{type:'p',cell:-1},{type:'p',cell:1.5}])assert.throws(()=>submitDeployment(g,0,order));g.board=[{id:'x',seat:0,type:'p',cell:0}];assert.throws(()=>submitDeployment(g,0,{type:'p',cell:0}));assert.throws(()=>submitDeployment(g,5,{type:'p',cell:1}));g.players[0].hand=['p'];assert.throws(()=>submitDeployment(g,0,{type:'q',cell:1}));});
test('simultaneous same-square clashes rotate priority and stolen pieces join the winning hand',()=>{for(let round=1;round<=4;round++){const g=newBattleground();g.round=round;for(let s=0;s<4;s++)submitDeployment(g,s,{type:'p',cell:44});resolveDeployments(g);assert.equal(g.board[0].seat,round-1);assert.equal(g.players[round-1].hand.length,14);assert.equal(g.events.filter(e=>e.kind==='clash').length,3);assert.deepEqual(g.orders,{});}});
test('landing takes an occupied enemy; ranged attacks respect blockers and pawn has four diagonals',()=>{const g=newBattleground();g.board=[{id:'enemy',seat:1,type:'q',cell:40},{id:'block',seat:0,type:'p',cell:22},{id:'far',seat:1,type:'q',cell:24}];assert.deepEqual(deploymentTargets(g,0,{type:'r',cell:20}),[40]);g.board=[{id:'a',seat:1,type:'n',cell:33},{id:'b',seat:2,type:'r',cell:55}];assert.deepEqual(deploymentTargets(g,0,{type:'p',cell:44}),[33,55]);g.board=[{id:'x',seat:1,type:'q',cell:40}];submitDeployment(g,0,{type:'p',cell:40});resolveDeployments(g);assert.ok(g.players[0].hand.includes('q'));assert.equal(g.board.find(p=>p.cell===40).seat,0);});
test('attacks are simultaneous trades; a last reserve capture saves its owner from elimination',()=>{const g=newBattleground();g.players[0].hand=['p'];g.players[1].hand=['p'];submitDeployment(g,0,{type:'p',cell:44});submitDeployment(g,1,{type:'p',cell:55});resolveDeployments(g);assert.equal(g.board.length,0);assert.equal(g.players[0].hand.length,1);assert.equal(g.players[1].hand.length,1);assert.equal(g.players[0].alive,true);assert.equal(g.players[1].alive,true);});
test('timeouts remove reserves, hand-empty eliminates board units and complete bot games terminate',()=>{const g=newBattleground();for(let i=0;i<12;i++)resolveDeployments(g);assert.deepEqual(g.result.winners,[]);assert.ok(g.players.every(p=>!p.alive));const bots=newBattleground();while(!bots.result){for(let s=0;s<4;s++){const order=botDeployment(bots,s,()=>0);if(order)submitDeployment(bots,s,order);}resolveDeployments(bots);}assert.ok(bots.round<=41);assert.equal(new Set(bots.board.map(p=>p.cell)).size,bots.board.length);});
test('three new skin identities survive purchases, per-piece equips, network validation and execution timing',()=>{assert.equal(shopCatalog.length,24);for(const skin of ['nova','phantom','dragon']){let profile=readProfile(null);profile.economy={...trialPremium(profile.economy).wallet,credits:2000};profile.economy=buyShopItem(profile.economy,`skin-${skin}`);assert.ok(isSkinUnlocked(profile,skin));profile=equipPiece(profile,'w','b1',skin);const saved=readProfile(JSON.stringify(profile));assert.equal(saved.loadouts.w.b1,skin);assert.equal(normalizeCosmetics({skin},'w').skin,skin);assert.ok(executionFrame(skin,.62).special);assert.equal(executionFrame(skin,1).strength,0);}assert.equal(readEconomy({owned:['dragon']}).owned[0],'dragon');});
async function service(t){const child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'0',GUEST_DUEL_ONLY:'true',BG_ROUND_MS:'1200'},stdio:['ignore','pipe','pipe']});t.after(()=>child.kill());const port=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server timeout')),5000);child.stdout.on('data',d=>{const m=String(d).match(/port (\d+)/);if(m){clearTimeout(timer);resolve(Number(m[1]));}});});async function peer(){const ws=new WebSocket(`ws://127.0.0.1:${port}/ws`),queue=[],waiters=[];t.after(()=>ws.terminate());ws.on('message',raw=>{const m=JSON.parse(raw),i=waiters.findIndex(w=>w.p(m));if(i>=0){const w=waiters.splice(i,1)[0];clearTimeout(w.timer);w.resolve(m);}else queue.push(m);});await once(ws,'open');return {ws,send:m=>ws.send(JSON.stringify(m)),wait:p=>{const i=queue.findIndex(p);if(i>=0)return Promise.resolve(queue.splice(i,1)[0]);return new Promise((resolve,reject)=>waiters.push({p,resolve,timer:setTimeout(()=>reject(Error('Missing BG message')),5000)}));}};}return {peer};}
test('actual four-device room gates readiness, hides orders, resolves captures, rejects stale rounds, resumes and rematches',async t=>{const server=await service(t),players=await Promise.all(Array.from({length:4},()=>server.peer()));players[0].send({type:'bg:create',roundSeconds:10,skin:'dragon'});const session=await players[0].wait(m=>m.type==='bg:session');for(let s=1;s<4;s++){players[s].send({type:'bg:join',code:session.code,skin:'phantom'});await players[s].wait(m=>m.type==='bg:session');}const fifth=await server.peer();fifth.send({type:'bg:join',code:session.code});assert.match((await fifth.wait(m=>m.type==='error')).message,/4 คน/);players[0].send({type:'bg:deploy',round:1,order:{type:'p',cell:0}});assert.match((await players[0].wait(m=>m.type==='error')).message,/เริ่ม/);for(const p of players)p.send({type:'bg:ready',ready:true});await players[0].wait(m=>m.type==='bg:state'&&m.started);players[0].send({type:'bg:deploy',round:1,order:{type:'p',cell:44}});const hidden=await players[1].wait(m=>m.type==='bg:state'&&m.submitted[0]);assert.deepEqual(hidden.game.orders,{});assert.equal(hidden.game.board.length,0);for(const p of players.slice(1))p.send({type:'bg:deploy',round:1,order:{type:'p',cell:44}});const resolved=await players[0].wait(m=>m.type==='bg:state'&&m.game.round===2);assert.equal(resolved.game.players[0].hand.length,14);assert.equal(resolved.game.events.filter(e=>e.kind==='clash').length,3);players[0].send({type:'bg:deploy',round:1,order:{type:'q',cell:55}});assert.match((await players[0].wait(m=>m.type==='error')).message,/รอบเปลี่ยน/);players[0].ws.close();await once(players[0].ws,'close');const resume=await server.peer();resume.send({type:'bg:resume',code:session.code,token:session.token});const back=await resume.wait(m=>m.type==='bg:state');assert.equal(back.game.id,resolved.game.id);assert.equal(back.members[0].skin,'dragon');assert.equal(back.started,true);for(const p of players.slice(1))p.send({type:'bg:leave'});const ended=await resume.wait(m=>m.type==='bg:state'&&m.game.result);assert.deepEqual(ended.game.result.winners,[0]);resume.send({type:'bg:rematch'});const rematch=await resume.wait(m=>m.type==='bg:state'&&!m.started);assert.notEqual(rematch.game.id,back.game.id);assert.equal(rematch.members[0].ready,false);});
