import assert from 'node:assert/strict';
import {readFileSync,existsSync,mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import {readProfile} from '../src/profile.ts';
import {enterMenu,chooseMode,launchPrepared,openPanel} from './enter-game.mjs';
const html=readFileSync('offline/Special-Chess-Offline.html','utf8'),url='http://localhost:31877/shop';
const browser=await chromium.launch({executablePath:existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const errors=[],external=[],shaderErrors=[];
const profile=readProfile(null);profile.economy.credits=2500;
try{
 const context=await browser.newContext({offline:true,viewport:{width:1100,height:850}}),page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/shader|VALIDATE_STATUS|THREE.WebGLProgram/i.test(m.text()))shaderErrors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith(url)&&/^https?:/.test(r.url()))external.push(r.url());});
 await page.route(url,r=>r.fulfill({contentType:'text/html',body:html}));await page.addInitScript(profile=>{if(!localStorage.getItem('shop-test')){localStorage.setItem('special-chess-profile',JSON.stringify(profile));localStorage.setItem('shop-test','1');}localStorage.setItem('special-chess-graphics-quality','low');localStorage.setItem('special-chess-reduced','true');window.WebSocket=class{constructor(){throw Error('Shop should be offline');}};},profile);
 const wallet=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('special-chess-profile')).economy);
 await page.goto(url);await enterMenu(page);await page.locator('[data-menu-go="treasury"]').click();assert.equal(await page.locator('.shop-card').count(),52);assert.equal(await page.locator('#wallet-premium').innerText(),'0');
 await page.locator('#shop-search').fill('หัวใจจักรกล');assert.equal(await page.locator('.shop-card:visible').count(),1);await page.locator('#shop-search').fill('');const original=await wallet();await page.locator('[data-shop-preview="skin-prism"]').click();await page.waitForSelector('#shop-preview-stage canvas');await page.locator('#shop-preview-piece').selectOption('q');await page.locator('#shop-preview-attack').click();await page.waitForTimeout(200);assert.deepEqual(await wallet(),original);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('special-chess-profile')).skin),'classic');assert.equal(await page.locator('#shop-confirm-buy').isDisabled(),true);
 mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/shop-trial-desktop.png'});await page.locator('#shop-dialog-close').click();for(const skin of ['nova','phantom','dragon']){await page.locator(`[data-shop-preview="skin-${skin}"]`).click();await page.waitForSelector('#shop-preview-stage canvas');await page.locator('#shop-preview-attack').click();await page.waitForTimeout(600);await page.locator('#shop-dialog-close').click();assert.deepEqual(await wallet(),original);}
 await page.locator('#premium-demo').click();await page.waitForTimeout(550);assert.equal((await wallet()).premium,300);assert.equal((await wallet()).credits,2500);assert.equal(await page.locator('#premium-demo').isDisabled(),true);
 await page.locator('[data-shop-buy="skin-prism"]').click();await page.locator('#shop-dialog-close').click();assert.equal((await wallet()).premium,300,'cancel does not spend');await page.locator('[data-shop-buy="skin-prism"]').click();await page.locator('#shop-confirm-buy').click();await page.waitForTimeout(550);assert.equal((await wallet()).premium,0);assert.equal((await wallet()).credits,2500);assert.ok((await wallet()).owned.includes('prism'));
 await page.locator('[data-shop-buy="bundle-storm"]').click();await page.locator('#shop-confirm-buy').click();await page.waitForTimeout(550);assert.equal((await wallet()).credits,1800);assert.equal((await wallet()).shards,40);assert.equal((await wallet()).premium,0);assert.equal(await page.locator('[data-shop-buy="skin-storm"]').isDisabled(),true);
 await page.locator('[data-shop-buy="shards-small"]').click();await page.locator('#shop-confirm-buy').click();await page.waitForTimeout(550);assert.equal((await wallet()).credits,1550);assert.equal((await wallet()).shards,70);
 await page.locator('#shop-filter').selectOption('premium');assert.equal(await page.locator('.shop-card.credits').count(),0);await page.locator('#shop-filter').selectOption('all');
 for(const viewport of [{width:390,height:844},{width:320,height:568},{width:844,height:390}]){await page.setViewportSize(viewport);await page.locator('.menu-page[data-menu-view="treasury"]').evaluate(el=>el.scrollTop=0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight+1),false);await page.screenshot({path:`test-results/shop-${viewport.width}.png`});}
 await page.setViewportSize({width:390,height:844});await page.locator('[data-shop-preview="skin-royal"]').click();await page.waitForSelector('#shop-preview-stage canvas');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'test-results/shop-trial-mobile.png'});await page.keyboard.press('Escape');await page.locator('#shop-item-dialog').waitFor({state:'hidden'});
 await page.reload();await enterMenu(page);await page.locator('[data-menu-go="treasury"]').click();assert.equal((await wallet()).premium,0);assert.equal((await wallet()).credits,1550);assert.equal(await page.locator('#premium-demo').isDisabled(),true);
 await page.setViewportSize({width:1100,height:850});await page.locator('#shop-open-arena').click();assert.match(await page.locator('#contract-brief').innerText(),/ชนะรับ 500/);await launchPrepared(page);const save=await page.evaluate(()=>JSON.parse(localStorage.getItem('special-chess-offline-game')));assert.equal(save.activeContract.mode,'open');assert.equal(save.mode,'bot');assert.equal((await wallet()).credits,1550);await openPanel(page,'pause');await page.locator('#resign').click();assert.equal((await wallet()).credits,1550,'immediate resignation earns no consolation');assert.equal((await wallet()).premium,0);
 // A legal completed Open match pays 500 once and remains safe on reload/undo.
 await page.evaluate(()=>{localStorage.setItem('special-chess-offline-game',JSON.stringify({mode:'bot',humanColor:'b',activeContract:{mode:'open',id:'open-browser-win'},initialFen:'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',history:['f3','e5','g4','Qh4#'],matchId:'open-browser-win'}));const profile=JSON.parse(localStorage.getItem('special-chess-profile'));profile.economy.claimed.push('entry:open:open-browser-win');localStorage.setItem('special-chess-profile',JSON.stringify(profile));});
 await page.reload();await enterMenu(page);assert.equal((await wallet()).credits,2050);assert.equal((await wallet()).premium,0);await page.reload();await enterMenu(page);assert.equal((await wallet()).credits,2050);await chooseMode(page,'battleground');await page.locator('#bg-bots').click();await page.waitForSelector('#bg-stage canvas');await page.waitForTimeout(100);assert.equal(await page.locator('[data-bg-piece="p"] svg').count(),1);await page.locator('#bg-close').click();await page.reload();await enterMenu(page);await page.locator('[data-menu-go="treasury"]').click();
 for(const [filter,count] of [['dimension',8],['finisher',8],['frame',12]]){await page.locator('#shop-filter').selectOption(filter);assert.equal(await page.locator('.shop-card').count(),count);assert.equal(await page.locator('.shop-card-art .cosmetic-sigil').count(),count);}
 await page.locator('#shop-filter').selectOption('all');
 for(const [id,kind] of [['dimension-solar','dimension'],['finisher-sunburst','finisher'],['frame-frame-1','frame']]){
  await page.locator(`[data-shop-buy="${id}"]`).click();await page.locator('#shop-confirm-buy').click();await page.waitForTimeout(550);
  assert.ok((await wallet()).inventory.includes(id));await page.locator(`[data-shop-equip="${id}"]`).click();assert.equal((await wallet()).equipped[kind],id);
 }
 assert.equal((await wallet()).credits,870);assert.equal(await page.locator('.commander-emblem .cosmetic-sigil').count(),1);
 await page.reload();await enterMenu(page);assert.equal((await wallet()).equipped.dimension,'dimension-solar');assert.equal((await wallet()).equipped.finisher,'finisher-sunburst');assert.equal((await wallet()).equipped.frame,'frame-frame-1');
 assert.deepEqual(shaderErrors,[]);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS: 52-item trial shop, locked skin 3D attack preview, cancellation, separate currencies, bundles/supplies, demo grant once, persistence, mobile layouts, free Open launch, no early resignation farming and actual 500-credit win once.');
}finally{await browser.close();}
