import {newBattleground,submitDeployment,resolveDeployments,botDeployment,deploymentTargets,bgTypes,bgColors,type BGGame,type Deployment} from '../shared/battleground.js';
import {claimCredits} from '../shared/economy.js';
import {skins,isSkinUnlocked,type SkinId,type Profile} from './profile';
import {pieceNames} from './cosmetics';
import {icon,geometricPiece} from './design';
import {duelEndpoint} from './online';
import {BattlegroundScene} from './battleground-scene';
import './battleground.css';
type Member={skin:SkinId;connected:boolean;ready:boolean};
interface BGState {type:'bg:state';code:string;seat:number;host:number;started:boolean;deadline:number;now:number;roundSeconds:number;game:BGGame;submitted:boolean[];members:(Member|null)[];}
export class Battleground {
 readonly root:HTMLElement;private game:BGGame|null=null;private scene?:BattlegroundScene;private socket?:WebSocket;private network=false;private state?:BGState;private seat=0;private selected:Deployment|null=null;private type=bgTypes[0];private deadline=0;private seconds=20;private members:(Member|null)[]=[null,null,null,null];private lastCue='';private endpoint='';private session?:{code:string;token:string;seat:number;endpoint:string};private retry?:ReturnType<typeof setTimeout>;private connecting=false;private generation=0;private lastSecond=-1;private lastRender='';
 constructor(host:HTMLElement,private profile:()=>Profile,private save:(profile:Profile)=>void,private pause:(open:boolean)=>void,private cue:(piece:string,skin:SkinId)=>void){
  this.root=document.createElement('section');this.root.id='battleground';this.root.hidden=true;this.root.innerHTML=`<header class="bg-header"><div><small>IAHCARUS / FOUR ARMIES</small><h1>BATTLEGROUND</h1></div><button id="bg-close">ออกจากสนาม</button></header><section id="bg-lobby"><h2>ศึกแย่งกองทัพ · 4 คน</h2><p>เริ่มคนละ 12 หมาก · วางได้ทุกช่องยกเว้นหมากตัวเอง · ทุกคนส่งคำสั่งลับแล้วเปิดพร้อมกัน · กินแล้วรับหมากนั้นเข้ามือ · มือหมดหลังตัดสินรอบถูกคัดออก</p><details><summary>กติกาที่ควรรู้</summary><p>ลงทับศัตรูจะยึดหมากทันที จากนั้นหมากที่ลงโจมตีศัตรูใกล้สุดหนึ่งตัวตามรูปแบบหมากรุก เบี้ยกินทแยงได้ทั้งสี่ทิศ คิงไม่ใช้กฎรุก หากวางชนกัน ลำดับสิทธิ์จะหมุนทุกตา การโจมตีคิดพร้อมกันจึงแลกชีวิตได้</p><p>ไม่ส่งคำสั่งในเวลาเสียหมากในมือหนึ่งตัว จำกัด 40 รอบแล้วตัดสินจากหมากในมือและจำนวนที่ยึดได้ ผู้แพ้ดูต่อได้ สกินไม่เพิ่มความสามารถ</p></details><div class="bg-lobby-controls"><label>เวลาต่อรอบ<select id="bg-time"><option value="10">10 วินาที</option><option value="20" selected>20 วินาที</option><option value="30">30 วินาที</option></select></label><label>สกินกองทัพ<select id="bg-skin"></select></label><button id="bg-bots">เล่นกับบอต 3 ตัว</button><button id="bg-connect">ออนไลน์ 4 คน</button></div><div id="bg-online" hidden><p id="bg-connection" role="status"></p><label>เซิร์ฟเวอร์<input id="bg-server" type="url" placeholder="https://iahcarus-duel.onrender.com"></label><div class="bg-room-actions"><button id="bg-create">สร้างห้อง</button><input id="bg-room-input" maxlength="6" aria-label="รหัสห้อง Battleground" placeholder="รหัส 6 ตัว"><button id="bg-join">จอยห้อง</button></div><strong id="bg-code"></strong><button id="bg-copy" hidden>คัดลอกลิงก์ชวนเพื่อน</button><button id="bg-ready" hidden>พร้อมประลอง</button></div></section><p id="bg-notice" role="status"></p><div id="bg-players"></div><section id="bg-battle" hidden><div class="bg-round"><strong id="bg-round"></strong><span id="bg-priority"></span><strong id="bg-clock"></strong></div><div id="bg-stage"></div><div id="bg-outcome" role="status" hidden></div><div class="bg-tactical-controls"><button id="bg-map-toggle">กระดานวางหมาก / คีย์บอร์ด</button><span id="bg-order-status"></span></div><div id="bg-map" hidden aria-label="ช่องวางหมาก">${Array.from({length:100},(_,i)=>`<button data-bg-cell="${i}" aria-label="ช่อง ${this.cellLabel(i)}"></button>`).join('')}</div><footer class="bg-hand"><div><small>YOUR RESERVE</small><strong id="bg-hand-count"></strong></div><div id="bg-hand"></div><button id="bg-lock">ล็อกช่องวาง</button></footer><div id="bg-feed" aria-live="polite"></div><button id="bg-again" hidden>เริ่มศึกใหม่</button></section>`;host.append(this.root);
  this.el<HTMLButtonElement>('#bg-close').onclick=()=>this.close();this.el<HTMLButtonElement>('#bg-bots').onclick=()=>this.startBots();this.el<HTMLButtonElement>('#bg-connect').onclick=()=>{this.network=true;this.el('#bg-online').hidden=false;this.connect();};
  this.el<HTMLButtonElement>('#bg-create').onclick=()=>this.send({type:'bg:create',roundSeconds:Number(this.el<HTMLSelectElement>('#bg-time').value),skin:this.skin()});
  this.el<HTMLButtonElement>('#bg-join').onclick=()=>this.send({type:'bg:join',code:this.el<HTMLInputElement>('#bg-room-input').value,skin:this.skin()});
  this.el<HTMLButtonElement>('#bg-ready').onclick=()=>this.send({type:'bg:ready',ready:!this.state?.members[this.seat]?.ready});
  this.el<HTMLSelectElement>('#bg-skin').onchange=()=>{if(this.session)this.send({type:'bg:equip',skin:this.skin()});};
  this.el<HTMLButtonElement>('#bg-lock').onclick=()=>this.lock();this.el<HTMLButtonElement>('#bg-map-toggle').onclick=()=>{this.el('#bg-map').hidden=!this.el('#bg-map').hidden;};
  this.root.querySelectorAll<HTMLButtonElement>('[data-bg-cell]').forEach(b=>b.onclick=()=>this.select(Number(b.dataset.bgCell)));
  this.el<HTMLButtonElement>('#bg-again').onclick=()=>{if(this.network)this.send({type:'bg:rematch'});else this.startBots();};
  this.el<HTMLButtonElement>('#bg-copy').onclick=async()=>{if(!this.state)return;const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('bg',this.state.code);url.searchParams.set('server',this.endpoint);try{await navigator.clipboard.writeText(url.href);this.notice('คัดลอกลิงก์ Battleground แล้ว');}catch{this.notice(`ชวนเพื่อนด้วยรหัส ${this.state.code}`);}};
  setInterval(()=>this.tick(),100);
 }
 private el<T extends HTMLElement=HTMLElement>(selector:string){return this.root.querySelector<T>(selector)!;}
 private cellLabel(cell:number){return 'ABCDEFGHIJ'[cell%10]+(10-Math.floor(cell/10));}
 private skin(){return this.el<HTMLSelectElement>('#bg-skin').value as SkinId;}
 private notice(message:string){this.el('#bg-notice').textContent=message;}
 open(invite?:string){this.lastRender='';this.root.hidden=false;this.pause(true);this.el<HTMLSelectElement>('#bg-skin').innerHTML=Object.keys(skins).filter(id=>isSkinUnlocked(this.profile(),id as SkinId)).map(id=>`<option value="${id}">${skins[id as SkinId].name}</option>`).join('');this.el<HTMLSelectElement>('#bg-skin').value=this.profile().skin;this.render();if(invite){this.el<HTMLInputElement>('#bg-room-input').value=invite;this.network=true;this.el('#bg-online').hidden=false;this.connect();}}
 private disconnect(clear=true){this.generation++;clearTimeout(this.retry);this.socket?.close();this.socket=undefined;this.connecting=false;if(clear){this.session=undefined;try{localStorage.removeItem('special-chess-bg-session');}catch{}}}
 close(){if(this.session)this.send({type:'bg:leave'});this.disconnect();this.game=null;this.state=undefined;this.selected=null;this.members=[null,null,null,null];this.network=false;this.el('#bg-online').hidden=true;this.root.hidden=true;this.scene?.setActive(false);this.pause(false);}
 private startBots(){if(this.session)this.send({type:'bg:leave'});this.disconnect();this.network=false;this.state=undefined;this.seat=0;this.seconds=Number(this.el<HTMLSelectElement>('#bg-time').value);this.game=newBattleground(crypto.randomUUID());this.members=[this.skin(),'nova','phantom','dragon'].map(skin=>({skin:skin as SkinId,connected:true,ready:true}));this.deadline=Date.now()+this.seconds*1000;this.selected=null;this.lastSecond=-1;this.notice('เลือกรูปหมากในมือ แล้วเลือกช่อง · เปลี่ยนคำสั่งได้จนหมดเวลา');this.render();}
 private async connect(){if(this.connecting||this.socket?.readyState===WebSocket.OPEN)return;this.connecting=true;const generation=++this.generation;this.el('#bg-connection').textContent='กำลังเชื่อมต่อ · เซิร์ฟเวอร์ฟรีอาจกำลังตื่น';
  let endpoint=duelEndpoint(this.el<HTMLInputElement>('#bg-server').value)||duelEndpoint(new URLSearchParams(location.search).get('server'))||duelEndpoint(localStorage.getItem('special-chess-duel-server'));
  if(!endpoint)try{const response=await fetch(new URL('online-config.json',location.href),{cache:'no-store',signal:AbortSignal.timeout(5000)});if(response.ok)endpoint=duelEndpoint((await response.json()).server);}catch{}
  if(generation!==this.generation)return;if(!endpoint){this.connecting=false;this.el('#bg-connection').textContent='ใส่ HTTPS ของเซิร์ฟเวอร์ แล้วกดออนไลน์อีกครั้ง';return;}
  this.endpoint=endpoint;this.el<HTMLInputElement>('#bg-server').value=endpoint;
  if(!this.session)try{const saved=JSON.parse(localStorage.getItem('special-chess-bg-session')||'null');if(saved?.endpoint===endpoint&&typeof saved.token==='string')this.session=saved;}catch{}
  const ws=new WebSocket(endpoint);this.socket=ws;ws.onopen=()=>{if(generation!==this.generation)return;this.connecting=false;this.el('#bg-connection').textContent='เชื่อมต่อแล้ว';this.render();if(this.session)this.send({type:'bg:resume',...this.session});else if(this.el<HTMLInputElement>('#bg-room-input').value)this.send({type:'bg:join',code:this.el<HTMLInputElement>('#bg-room-input').value,skin:this.skin()});};
  ws.onmessage=e=>{if(generation!==this.generation)return;try{const data=JSON.parse(e.data);if(data.type==='error'){this.notice(data.message);if(this.session&&!this.state){this.session=undefined;localStorage.removeItem('special-chess-bg-session');}return;}if(data.type==='bg:replaced'){this.disconnect();this.notice('ที่นั่งนี้เปิดอยู่ในอีกแท็บ');return;}if(data.type==='bg:session'){this.session={code:data.code,token:data.token,seat:data.seat,endpoint:this.endpoint};localStorage.setItem('special-chess-bg-session',JSON.stringify(this.session));}if(data.type==='bg:state'){const next=data as BGState,changed=this.game?.round!==next.game.round||this.game?.id!==next.game.id;this.state=next;this.game=next.game;this.members=next.members;this.seat=next.seat;this.seconds=next.roundSeconds;this.deadline=Date.now()+Math.max(0,next.deadline-next.now);if(changed)this.selected=null;this.render();}}catch{this.notice('ข้อมูลห้องไม่ถูกต้อง');}};
  ws.onclose=()=>{if(generation!==this.generation||this.root.hidden)return;this.connecting=false;this.el('#bg-connection').textContent='หลุดการเชื่อมต่อ · เวลารอบยังเดินต่อ';this.notice('หลุดการเชื่อมต่อ · รอบยังเดินต่อ กำลังกู้ที่นั่ง');this.render();this.retry=setTimeout(()=>this.connect(),3000);};ws.onerror=()=>this.notice('เชื่อมต่อไม่สำเร็จ · ตรวจว่า Render deploy ล่าสุดแล้ว');
 }
 private send(message:object){if(this.socket?.readyState!==WebSocket.OPEN){this.notice('รอการเชื่อมต่อเซิร์ฟเวอร์');return false;}this.socket.send(JSON.stringify(message));return true;}
 private select(cell:number){if(!this.game||this.game.result||!this.game.players[this.seat]?.alive)return;if(this.game.board.some(p=>p.cell===cell&&p.seat===this.seat)){this.notice('เลือกช่องว่างหรือช่องศัตรู');return;}this.selected={type:this.type,cell};this.render();}
 private lock(){if(!this.game||!this.selected)return;try{if(this.network)this.send({type:'bg:deploy',round:this.game.round,order:this.selected});else{submitDeployment(this.game,this.seat,this.selected);this.notice('ล็อกแล้ว · ยังเปลี่ยนหมากและส่งใหม่ได้ก่อนหมดเวลา');this.render();}}catch(e){this.notice((e as Error).message);}}
 private tick(){if(this.root.hidden||!this.game||this.network&&!this.state?.started||this.game.result)return;if(!this.network&&Date.now()>=this.deadline){for(let i=1;i<4;i++){const order=botDeployment(this.game,i);if(order)submitDeployment(this.game,i,order);}resolveDeployments(this.game);this.selected=null;this.deadline=Date.now()+this.seconds*1000;this.render();}const second=Math.max(0,Math.ceil((this.deadline-Date.now())/1000));if(second!==this.lastSecond){this.lastSecond=second;this.el('#bg-clock').textContent=`${second}s`;}}
 private render(){
  const signature=JSON.stringify([this.game?.id,this.game?.revision,this.game?.orders,this.members,this.selected,this.type,this.network,this.socket?.readyState,this.session,this.state?.started,this.state?.submitted,this.state?.host]);if(signature===this.lastRender)return;this.lastRender=signature;
  const started=!!this.game&&(!this.network||!!this.state?.started);this.root.classList.toggle('bg-playing',started);this.scene?.setActive(started);this.el('#bg-lobby').hidden=started;this.el('#bg-battle').hidden=!started;this.el('#bg-players').innerHTML=this.members.map((m,i)=>`<article style="--seat:${bgColors[i]}"><strong>${i===this.seat?'คุณ':this.network?`ผู้เล่น ${i+1}`:`บอต ${i}`} · ${m?skins[m.skin].name:'รอเพื่อน'}</strong><span>${started?`${this.game!.players[i].alive?'อยู่ในสนาม':'ตกรอบ'} · มือ ${this.game!.players[i].hand.length} · ยึด ${this.game!.players[i].captured}`:m?`${m.connected?'เชื่อมต่อ':'หลุด'} · ${m.ready?'พร้อม':'กำลังเตรียม'}`:'ว่าง'}</span></article>`).join('');
  const connected=this.socket?.readyState===WebSocket.OPEN;for(const id of ['#bg-create','#bg-join'])this.el<HTMLButtonElement>(id).disabled=!connected||!!this.session;this.el<HTMLInputElement>('#bg-server').disabled=!!this.session;this.el<HTMLSelectElement>('#bg-time').disabled=!!this.session;this.el<HTMLSelectElement>('#bg-skin').disabled=started;this.el('#bg-ready').hidden=!this.session||started;this.el<HTMLButtonElement>('#bg-ready').disabled=!connected;this.el('#bg-ready').textContent=this.state?.members[this.seat]?.ready?'ยกเลิกพร้อม':'พร้อมประลอง';this.el('#bg-copy').hidden=!this.session;this.el('#bg-code').textContent=this.session?`ห้อง ${this.session.code} · ที่นั่ง ${this.seat+1}/4`:'';
  if(!started||!this.game)return;
  const game=this.game,player=game.players[this.seat];const cueKey=`${game.id}:${game.revision}`;if(this.lastCue!==cueKey){this.lastCue=cueKey;const event=game.events.find(e=>e.kind==='capture'||e.kind==='clash');if(event)this.cue(event.attackerType||'n',this.members[event.seat]?.skin||'classic');}if(!player.hand.includes(this.type))this.type=player.hand[0]||'p';
  this.el('#bg-round').textContent=`รอบ ${Math.min(40,game.round)} / 40`;this.el('#bg-priority').textContent=`สิทธิ์ช่องชนเริ่มจากผู้เล่น ${(game.round-1)%4+1}`;
  this.el('#bg-hand-count').textContent=`${player.hand.length} หมาก${player.alive?'':' · ดูต่อได้'}`;this.el('#bg-hand').innerHTML=bgTypes.map(type=>`<button data-bg-piece="${type}" aria-label="เลือก${pieceNames[type]}" aria-pressed="${type===this.type}" ${!player.alive||!player.hand.includes(type)||game.result?'disabled':''}>${geometricPiece(type,'w')}<small>${pieceNames[type]} ${player.hand.filter(p=>p===type).length}</small></button>`).join('');this.root.querySelectorAll<HTMLButtonElement>('[data-bg-piece]').forEach(b=>b.onclick=()=>{this.type=b.dataset.bgPiece as typeof this.type;if(this.selected)this.selected.type=this.type;this.render();});
  const targets=this.selected?deploymentTargets(game,this.seat,this.selected):[];this.root.querySelectorAll<HTMLButtonElement>('[data-bg-cell]').forEach(b=>{const cell=Number(b.dataset.bgCell),unit=game.board.find(p=>p.cell===cell);b.innerHTML=unit?geometricPiece(unit.type,unit.seat%2?'b':'w'):'';b.style.color=unit?bgColors[unit.seat]:'';b.classList.toggle('selected',this.selected?.cell===cell);b.classList.toggle('target',targets.includes(cell));b.disabled=!player.alive||!!game.result||unit?.seat===this.seat;b.title=this.cellLabel(cell)+(unit?` · ผู้เล่น ${unit.seat+1} ${pieceNames[unit.type]}`:'');});
  const locked=game.orders[this.seat],submitted=this.network?this.state?.submitted.filter(Boolean).length:Object.keys(game.orders).length;this.el('#bg-order-status').textContent=game.result?'ศึกจบแล้ว':!player.alive?'มือหมด · ดูผู้รอดชีวิตต่อ':`ส่งคำสั่ง ${submitted}/4${locked?` · ล็อก ${pieceNames[locked.type]} ${this.cellLabel(locked.cell)}`:' · ยังไม่ได้ส่ง'}${this.selected?` · เลือก ${this.cellLabel(this.selected.cell)}`:''}`;this.el<HTMLButtonElement>('#bg-lock').disabled=!this.selected||!player.alive||!!game.result||this.network&&!connected;
  this.el('#bg-feed').textContent=game.events.map(e=>e.kind==='capture'||e.kind==='clash'?`ผู้เล่น ${e.seat+1} ยึด${pieceNames[e.type!]}จาก ${e.victim!+1}`:e.kind==='eliminated'?`ผู้เล่น ${e.seat+1} มือหมด`:e.kind==='timeout'?`ผู้เล่น ${e.seat+1} หมดเวลา เสียหมาก`:'' ).filter(Boolean).join(' · ');
  this.el('#bg-outcome').hidden=!game.result;this.el('#bg-again').hidden=!game.result||this.network&&this.state?.host!==this.seat;
  if(game.result){const won=game.result.winners.includes(this.seat);this.el('#bg-outcome').textContent=won?'VICTORY · กองทัพของคุณรอดชีวิต':game.result.winners.length?`ผู้เล่น ${game.result.winners.map(s=>s+1).join(', ')} ชนะ · เริ่มศึกใหม่ได้`:'ทุกคนมือหมด · เสมอ';const profile=this.profile(),amount=won?650:game.round>=4?100:0;const reward=claimCredits(profile.economy,`bg:${game.id}`,amount,'รางวัล Battleground');if(reward.added)this.save({...profile,economy:reward.wallet});}
  try{this.scene ||=new BattlegroundScene(this.el('#bg-stage'),cell=>this.select(cell));this.scene.render(game,this.members.map(m=>m?.skin||'classic'),this.selected?.cell??null,targets);}catch{this.el('#bg-map').hidden=false;this.notice('ใช้กระดานวางหมากแทนพรีวิว 3D บนเครื่องนี้');}
 }
}
