import { skins, isSkinUnlocked, type Profile, type SkinId } from "./profile";
import { skinPool, pullCost, pityLimit, forgeCosts, shopCatalog, type ShopItem } from "../shared/economy.js";
import { icon, geometricPiece } from "./design";
import { utcDay } from "./daily";
import "./economy.css";
export type EconomyAction = { type: "pull" } | { type: "daily" } | { type: "forge"; skin: SkinId } | { type: "buy"; product: string } | { type: "premium-demo" };
const escape = (value: string) => value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]!));
export function treasuryHTML(profile: Profile, message = "ทดลองสกินก่อนซื้อ · เลือกสกุลเงินและสินค้าที่ต้องการ", busy = false, filter = "all") {
  const wallet = profile.economy;
  return `<div class="wallet-balances"><article><span class="currency-mark">${icon("citadel")}</span><div><small>เครดิต · จากการเล่น</small><strong id="wallet-credits">${wallet.credits.toLocaleString("en-US")}</strong></div></article><article class="premium-balance"><span class="currency-mark violet">${icon("eclipse")}</span><div><small>พรีเมียม · ทดลอง</small><strong id="wallet-premium">${wallet.premium.toLocaleString("en-US")}</strong></div></article><article><span class="currency-mark violet">${icon("astral")}</span><div><small>เศษพลังงาน</small><strong id="wallet-shards">${wallet.shards.toLocaleString("en-US")}</strong></div></article></div>
    <p class="economy-note">ร้านค้าทดลอง · ไม่มีการจ่ายเงินจริง · เครดิตได้จากการเล่น พรีเมียมแยกยอดต่างหาก · เศษพลังงานใช้หลอมสกิน · เซฟในเครื่องนี้</p>
    <div class="shop-tools"><label>เลือกสินค้า<select id="shop-filter"><option value="all" ${filter==='all'?'selected':''}>ทั้งหมด</option><option value="credits" ${filter==='credits'?'selected':''}>ซื้อด้วยเครดิต</option><option value="premium" ${filter==='premium'?'selected':''}>ซื้อด้วยพรีเมียม</option><option value="bundle" ${filter==='bundle'?'selected':''}>ชุดธีม</option><option value="supplies" ${filter==='supplies'?'selected':''}>เสบียงและวัสดุ</option></select></label><button id="premium-demo" data-economy-action="premium-demo" ${busy||wallet.claimed.includes('trial:premium-v1')?'disabled':''}>${wallet.claimed.includes('trial:premium-v1')?'รับพรีเมียมทดลองแล้ว':'รับพรีเมียมทดลอง +300 · ครั้งเดียว'}</button><button id="shop-open-arena">${icon("challenge")} เล่น Open · หาเครดิต</button></div>
    <section class="shop-catalog"><small>ARMY EXCHANGE / ${shopCatalog.length} ITEMS</small><h2>เลือกของให้กองทัพคุณ</h2><div class="shop-grid">${shopCatalog.filter(item=>filter==='all'||item.currency===filter||item.kind===filter).map(item=>shopCard(profile,item,busy)).join('')}</div></section>
    <section class="seal-chamber ${busy ? "revealing" : ""}"><div class="seal-art" aria-hidden="true"><i></i><i></i><span>${geometricPiece("q", "w")}</span></div><div><small>ASTRAL RELIQUARY</small><h2>ผนึกกองทัพดวงดาว</h2><p>สุ่มชุดกองทัพที่ใช้ได้กับหมากทุกตัว<br>สกินซ้ำเปลี่ยนเป็นเศษพลังงาน</p><button id="skin-pull" data-economy-action="pull" class="primary" ${busy || wallet.credits < pullCost ? "disabled" : ""}>${icon("shuffle")} เปิดผนึก · ${pullCost} เครดิต</button><p id="skin-pity">อีก ${pityLimit - wallet.pity} ครั้งรับ Golden Sovereign แน่นอน · ได้ตำนาน/มายาธิคแล้วนับใหม่</p></div></section>
    <p id="economy-status" class="economy-status" role="status" aria-live="polite">${escape(message)}</p>
    <div class="skin-odds">${skinPool.map(item => `<span style="--skin-glow:${skins[item.skin].glow}"><i></i><strong>${skins[item.skin].name}</strong><small>${wallet.pity >= pityLimit - 1 ? item.skin === "royal" ? 100 : 0 : item.chance}% · ซ้ำ +${item.shards} เศษ</small></span>`).join("")}</div>
    <button id="daily-credits" data-economy-action="daily" ${wallet.claimed.includes(`login:${utcDay()}`) || busy ? "disabled" : ""}>${icon("challenge")} ${wallet.claimed.includes(`login:${utcDay()}`) ? "รับเสบียงวันนี้แล้ว" : "รับเสบียงประจำวัน +100 เครดิต"}</button>
    <section class="forge"><small>CHOOSE YOUR LEGACY</small><h2>หลอมสกินที่เลือกเอง</h2><div>${skinPool.map(item => `<button data-economy-action="forge" data-forge-skin="${item.skin}" style="--skin-glow:${skins[item.skin].glow}" ${busy || isSkinUnlocked(profile, item.skin) || wallet.shards < forgeCosts[item.skin]! ? "disabled" : ""}><span>${geometricPiece("n", "w")}</span><strong>${skins[item.skin].name}</strong><small>${isSkinUnlocked(profile, item.skin) ? "มีสกินแล้ว" : `${forgeCosts[item.skin]} เศษพลังงาน`}</small></button>`).join("")}</div></section>
    <section class="wallet-history"><h2>รายการล่าสุด</h2>${wallet.log.slice(-8).reverse().map(item => `<div><span>${escape(item.label)}</span><strong>${item.delta > 0 ? "+" : ""}${item.delta} ${item.currency === "premium" ? "พรีเมียม" : "เครดิต"}</strong></div>`).join("") || "<p>เริ่มเล่นเพื่อสร้างเรื่องราวของคลังคุณ</p>"}</section>`;
}

export function shopName(item:ShopItem){return item.skin?`${item.kind==='bundle'?'ชุดธีม':'สกิน'} ${skins[item.skin].name}`:item.label!;}
function shopCard(profile:Profile,item:ShopItem,busy:boolean){
 const owned=!!item.skin&&isSkinUnlocked(profile,item.skin),skin=item.skin?skins[item.skin]:null;
 return `<article class="shop-card ${item.currency}" style="--skin-glow:${skin?.glow||'#85edff'}"><div class="shop-card-art" aria-hidden="true">${item.skin?geometricPiece('n','w'):icon('citadel')}</div><small>${skin?skin.rarity.toUpperCase():'SUPPLIES'} / ${item.kind==='bundle'?'THEME SET':item.kind==='skin'?'ARMY SKIN':'RESOURCE PACK'}</small><h3>${shopName(item)}</h3><p>${item.skin?'ใช้ได้กับหมากทุกตัว · โมเดล ออร่า เสียงและเอฟเฟกต์ตามสกิน':'เพิ่มเข้ากระเป๋าทันทีหลังยืนยัน'}${item.shards?` · +${item.shards} เศษพลังงาน`:''}</p><strong class="shop-price">${item.price.toLocaleString('en-US')} ${item.currency==='premium'?'พรีเมียม':'เครดิต'}</strong><div>${item.skin?`<button data-shop-preview="${item.id}" ${busy?'disabled':''}>ทดลอง 3D</button>`:''}<button data-shop-buy="${item.id}" ${busy||owned||profile.economy[item.currency]<item.price?'disabled':''}>${owned?'มีสกินแล้ว':'ซื้อสินค้า'}</button></div></article>`;
}
