import {cosmeticArt} from './presentation-art';
import { skins, isSkinUnlocked, type Profile, type SkinId } from "./profile";
import { skinPool, pullCost, pityLimit, forgeCosts, shopCatalog, type ShopItem, gachaBanners, bannerPool, bannerOdds, capsuleCost, lootRarity, cosmeticForgeCosts, type LootReward } from "../shared/economy.js";
import { icon, geometricPiece } from "./design";
import { utcDay } from "./daily";
import "./economy.css";
export type EconomyAction = { type: "pull" } | {type:"capsule";banner:string;count:number} | {type:"forge-cosmetic";product:string} | { type: "daily" } | { type: "forge"; skin: SkinId } | { type: "buy"; product: string } | { type: "premium-demo" } | {type:"equip";product:string};
const escape = (value: string) => value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]!));
export function treasuryHTML(profile: Profile, message = "ทดลองสกินก่อนซื้อ · เลือกสกุลเงินและสินค้าที่ต้องการ", busy = false, filter = "all", banner = "collection") {
  const wallet = profile.economy;
  return `<div class="wallet-balances"><article><span class="currency-mark">${icon("citadel")}</span><div><small>เครดิต · จากการเล่น</small><strong id="wallet-credits">${wallet.credits.toLocaleString("en-US")}</strong></div></article><article class="premium-balance"><span class="currency-mark violet">${icon("eclipse")}</span><div><small>พรีเมียม · ทดลอง</small><strong id="wallet-premium">${wallet.premium.toLocaleString("en-US")}</strong></div></article><article><span class="currency-mark violet">${icon("astral")}</span><div><small>เศษพลังงาน</small><strong id="wallet-shards">${wallet.shards.toLocaleString("en-US")}</strong></div></article></div>
    <p class="economy-note">ร้านค้าทดลอง · ไม่มีการจ่ายเงินจริง · เครดิตได้จากการเล่น พรีเมียมแยกยอดต่างหาก · เศษพลังงานใช้หลอมสกินและเครื่องแต่ง · เซฟในเครื่องนี้</p>
    <div class="shop-tools"><label>ค้นหาร้านค้า<input id="shop-search" type="search" maxlength="80" placeholder="ชื่อ ธีม หรือประเภท" aria-label="ค้นหาสินค้า"></label><label>เลือกสินค้า<select id="shop-filter"><option value="all" ${filter==='all'?'selected':''}>ทั้งหมด</option><option value="owned" ${filter==='owned'?'selected':''}>ของที่มีแล้ว</option><option value="skin" ${filter==='skin'?'selected':''}>สกินกองทัพ</option><option value="credits" ${filter==='credits'?'selected':''}>ซื้อด้วยเครดิต</option><option value="premium" ${filter==='premium'?'selected':''}>ซื้อด้วยพรีเมียม</option>${['dimension','finisher','frame','board','skill'].map(kind=>`<option value="${kind}" ${filter===kind?'selected':''}>${{dimension:'มิติต่อสู้',finisher:'เอฟเฟกต์ปิดฉาก',frame:'กรอบโปรไฟล์',board:'ลายกระดาน',skill:'เอฟเฟกต์สกิล'}[kind]}</option>`).join('')}<option value="bundle" ${filter==='bundle'?'selected':''}>ชุดธีม</option><option value="supplies" ${filter==='supplies'?'selected':''}>เสบียงและวัสดุ</option></select></label><button id="premium-demo" data-economy-action="premium-demo" ${busy||wallet.claimed.includes('trial:premium-v1')?'disabled':''}>${wallet.claimed.includes('trial:premium-v1')?'รับพรีเมียมทดลองแล้ว':'รับพรีเมียมทดลอง +300 · ครั้งเดียว'}</button><button id="shop-open-arena">${icon("challenge")} เล่น Open · หาเครดิต</button></div>
    ${capsuleHTML(profile,banner,busy)}
    <section class="shop-catalog"><small>ARMY EXCHANGE / ${shopCatalog.length} ITEMS</small><h2>เลือกของให้กองทัพคุณ</h2><div class="shop-grid">${shopCatalog.filter(item=>filter==='all'||item.currency===filter||item.kind===filter||filter==='owned'&&(item.cosmetic?wallet.inventory.includes(item.id):item.skin&&isSkinUnlocked(profile,item.skin))).map(item=>shopCard(profile,item,busy)).join('')}</div></section>
    <section class="seal-chamber ${busy ? "revealing" : ""}"><div class="seal-art" aria-hidden="true"><i></i><i></i><span>${geometricPiece("q", "w")}</span></div><div><small>LEGACY RELIQUARY / เก็บการันตีผนึกเดิมไว้</small><h2>ผนึกกองทัพดวงดาว</h2><p>สุ่มชุดกองทัพที่ใช้ได้กับหมากทุกตัว<br>สกินซ้ำเปลี่ยนเป็นเศษพลังงาน</p><button id="skin-pull" data-economy-action="pull" class="primary" ${busy || wallet.credits < pullCost ? "disabled" : ""}>${icon("shuffle")} เปิดผนึก · ${pullCost} เครดิต</button><p id="skin-pity">อีก ${pityLimit - wallet.pity} ครั้งรับ Golden Sovereign แน่นอน · ได้ตำนาน/มายาธิคแล้วนับใหม่</p></div></section>
    <p id="economy-status" class="economy-status" role="status" aria-live="polite">${escape(message)}</p>
    <div class="skin-odds">${skinPool.map(item => `<span style="--skin-glow:${skins[item.skin].glow}"><i></i><strong>${skins[item.skin].name}</strong><small>${wallet.pity >= pityLimit - 1 ? item.skin === "royal" ? 100 : 0 : item.chance}% · ซ้ำ +${item.shards} เศษ</small></span>`).join("")}</div>
    <button id="daily-credits" data-economy-action="daily" ${wallet.claimed.includes(`login:${utcDay()}`) || busy ? "disabled" : ""}>${icon("challenge")} ${wallet.claimed.includes(`login:${utcDay()}`) ? "รับเสบียงวันนี้แล้ว" : "รับเสบียงประจำวัน +100 เครดิต"}</button>
    <section class="forge"><small>CHOOSE YOUR LEGACY</small><h2>หลอมสกินที่เลือกเอง</h2><div>${skinPool.map(item => `<button data-economy-action="forge" data-forge-skin="${item.skin}" style="--skin-glow:${skins[item.skin].glow}" ${busy || isSkinUnlocked(profile, item.skin) || wallet.shards < forgeCosts[item.skin]! ? "disabled" : ""}><span>${geometricPiece("n", "w")}</span><strong>${skins[item.skin].name}</strong><small>${isSkinUnlocked(profile, item.skin) ? "มีสกินแล้ว" : `${forgeCosts[item.skin]} เศษพลังงาน`}</small></button>`).join("")}</div></section>
    <section class="wallet-history"><h2>รายการล่าสุด</h2>${wallet.log.slice(-8).reverse().map(item => `<div><span>${escape(item.label)}</span><strong>${item.delta > 0 ? "+" : ""}${item.delta} ${item.currency === "premium" ? "พรีเมียม" : "เครดิต"}</strong></div>`).join("") || "<p>เริ่มเล่นเพื่อสร้างเรื่องราวของคลังคุณ</p>"}</section>`;
}

export function shopName(item:ShopItem){return item.skin?`${item.kind==='bundle'?'ชุดธีม':'สกิน'} ${skins[item.skin].name}`:item.label!;}
function shopCard(profile:Profile,item:ShopItem,busy:boolean){
 const owned=item.cosmetic?profile.economy.inventory.includes(item.id):!!item.skin&&isSkinUnlocked(profile,item.skin),skin=item.skin?skins[item.skin]:null;
 return `<article class="shop-card ${item.currency}" style="--skin-glow:${skin?.glow||item.color||'#85edff'}"><div class="shop-card-art" aria-hidden="true">${item.cosmetic?cosmeticArt(item):item.skin?geometricPiece('n','w'):icon('citadel')}</div><small>${skin?skin.rarity.toUpperCase():item.cosmetic?lootRarity(item).toUpperCase():'SUPPLIES'} / ${item.kind==='bundle'?'THEME SET':item.kind==='skin'?'ARMY SKIN':item.cosmetic?item.kind.toUpperCase():'RESOURCE PACK'}</small><h3>${shopName(item)}</h3><p>${item.skin?'ใช้ได้กับหมากทุกตัว · โมเดล ออร่า เสียงและเอฟเฟกต์ตามสกิน':item.description||(item.cosmetic?'ใช้กับคัตซีนหมากรุก':'เพิ่มเข้ากระเป๋าทันทีหลังยืนยัน')}${item.shards?` · +${item.shards} เศษพลังงาน`:''}</p><strong class="shop-price">${item.price.toLocaleString('en-US')} ${item.currency==='premium'?'พรีเมียม':'เครดิต'}</strong><div>${item.skin||item.cosmetic?`<button data-shop-preview="${item.id}" ${busy?'disabled':''}>${item.skin?'ทดลอง 3D':'ดูรายละเอียด'}</button>`:''}<button data-shop-buy="${item.id}" ${busy||owned||profile.economy[item.currency]<item.price?'disabled':''}>${owned?'มีแล้ว':'ซื้อสินค้า'}</button>${item.cosmetic&&!owned?`<button data-cosmetic-forge="${item.id}" ${busy||profile.economy.shards<cosmeticForgeCosts[lootRarity(item)]?'disabled':''}>หลอม · ${cosmeticForgeCosts[lootRarity(item)]} เศษ</button>`:''}${item.cosmetic&&owned?`<button data-shop-equip="${item.id}" ${busy?'disabled':''}>${profile.economy.equipped[item.kind as 'dimension'|'finisher'|'frame'|'board'|'skill']===item.id?'ถอดออก':'สวมใช้งาน'}</button>`:''}</div></article>`;
}

export function lootCard(reward:LootReward){
 const item=shopCatalog.find(v=>v.id===reward.product)!;
 return `<article class="loot-card rarity-${reward.rarity}"><small>${reward.rarity.toUpperCase()}${reward.guaranteed?' / GUARANTEED':''}</small><div>${item.cosmetic?cosmeticArt(item):geometricPiece('n','w')}</div><strong>${shopName(item)}</strong><p>${reward.duplicate?`ของซ้ำ → +${reward.shards} เศษพลังงาน`:'ของใหม่ · เพิ่มเข้าคลังแล้ว'}</p>${item.cosmetic?`<button data-reward-equip="${item.id}">สวมใช้งาน</button>`:'<small>สวมในคลังแสง</small>'}</article>`;
}
function capsuleHTML(profile:Profile,banner:string,busy:boolean){
 const wallet=profile.economy,definition=gachaBanners.find(v=>v.id===banner)!,pool=bannerPool(banner),odds=bannerOdds(banner,wallet),pity=wallet.bannerPity[banner];
 const normalOdds=bannerOdds(banner),rates=['common','rare','epic','legendary'].map(r=>`${r.toUpperCase()} ${normalOdds.filter(v=>v.rarity===r).reduce((sum,v)=>sum+v.chance,0).toFixed(2)}%`).join(' · ');
 const latest=wallet.lootHistory.slice(-10).reverse();
 return `<section class="capsule-hub"><header><small>RELIQUARY / COLLECTION CAPSULES</small><h2>เปิดคลังจักรวาล</h2><p>ทุกชิ้นเป็นของแต่ง ไม่มีผลต่อพลังหรือกติกา · ใช้เครดิตจากการเล่น</p></header><div class="banner-tabs" role="group" aria-label="เลือกตู้สุ่ม">${gachaBanners.map(v=>`<button data-gacha-banner="${v.id}" aria-pressed="${banner===v.id}">${v.label}</button>`).join('')}</div><div class="capsule-focus"><div class="capsule-emblem">${cosmeticArt({kind:'dimension',pattern:gachaBanners.indexOf(definition)+4,color:'#b5cbff'})}</div><div><h3>${definition.label}</h3><p>${definition.description} · ${pool.length} รางวัล</p><p>ทุก 10 ครั้งได้ Rare ขึ้นไป · ภายใน 20 ครั้งได้ Legendary<br>แยกการันตีแต่ละตู้ · สะสมต่อได้ · ได้ระดับนั้นก่อนถึงกำหนดจะเริ่มนับใหม่</p><div class="pity-track"><span>Legendary ภายในอีก ${20-pity.legend} ครั้ง</span><progress value="${pity.legend}" max="20"></progress><small>Rare ขึ้นไปภายในอีก ${10-pity.rare} ครั้ง</small></div><div class="capsule-actions"><button class="primary" data-capsule-count="1" ${busy||wallet.credits<capsuleCost?'disabled':''}>เปิด 1 · ${capsuleCost} เครดิต</button><button data-capsule-count="10" ${busy||wallet.credits<capsuleCost*10?'disabled':''}>เปิด 10 · ${capsuleCost*10} เครดิต</button></div><p class="economy-note">10 ครั้งราคาเท่ากับเปิดทีละชิ้น · ของซ้ำ Common 15 / Rare 35 / Epic 80 / Legendary 160 เศษ · ใช้หลอมของที่เลือกเอง</p></div></div><details class="capsule-odds"><summary>ดูรางวัลและโอกาสออกจริงของการเปิดครั้งถัดไป</summary><p>อัตราปกติของตู้นี้: ${rates} · เมื่อถึงการันตีปรับสัดส่วนตามรายการด้านล่าง · ในชุด 10 ครั้งโอกาสปรับหลังทุกชิ้น</p><div>${odds.map(v=>{const item=pool.find(item=>item.id===v.product)!;return `<span><b>${shopName(item)}</b><small>${v.rarity.toUpperCase()} · ${v.chance.toFixed(3)}%</small></span>`;}).join('')}</div></details>${latest.length?`<details class="capsule-history"><summary>รางวัลสุ่มล่าสุด · เซฟแล้ว</summary><div class="loot-grid">${latest.map(v=>lootCard(v)).join('')}</div></details>`:''}</section>`;
}
